### ISSUE TITLE
2 GRAV REPOS !!!!

### ISSUE THREAD

**Issue by frju365** [YunoHost-Apps/grav_ynh#1]
There are 2 grav_ynh repos  for one app. I think you need to contact @lithrel to have the same repos with the commits of all repos. A mail contact will be fine too. I added you to the grav Team to have a better team work.

**Comment by frju365** [comment]
Once you agree to create a new repos with all the commit I will add this repos to the team.

**Comment by magikcypress** [comment]
The README is correct on the @lithrel repository and adding plugins is a good thing.
A pull request can be made on YunoHost-Apps code for to check with package check.

**Comment by frju365** [comment]
ok. I will do a test this weekend(or tomorrow) on each app.

**Comment by magikcypress** [comment]
Ok, good !

**Comment by frju365** [comment]
Is the problem solved or not ?

**Comment by magikcypress** [comment]
not for the moment

**Comment by frju365** [comment]
ok...  You must try to find a in-between repos, with all the commit of each repos (PLEASE !!!!) and the conflict resolved !

**Comment by frju365** [comment]
As this problem is solved apparently. Closed !
