### ISSUE TITLE
E: Unable to locate package grav-ynh-deps

### ISSUE THREAD

**Issue by JamesCenter** [YunoHost-Apps/grav_ynh#105]
Hello.
I found I cannot uninstall it on my servers. It is still display Grav on my domain.
When I uninstall it:
``E: Unable to locate package grav-ynh-deps``

**Comment by tituspijean** [comment]
Please read the issue template you have blatantly ignored. We need more information to properly help you.

**Comment by JamesCenter** [comment]
# Describe the bug

Cannot uninstall Grav.

# Context

- Hardware: *VPS bought online*
- YunoHost version: 4.3.6.2 (stable)
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

# Steps to reproduce
I found I cannot uninstall it on my servers. It is still display Grav on my domain.

# Logs
https://paste.yunohost.org/raw/vegituruni

**Comment by tituspijean** [comment]
The log looks fine to me, the app should be removed. When you say "It is still display Grav on my domain.", do you mean it still appears in the user interface and the admin panel? Are you sure it is not a second Grav app?

**Comment by tituspijean** [comment]
@JamesCenter do you have any feedback on this?

**Comment by yalh76** [comment]
Fell free to reopen that issue
