### ISSUE TITLE
Consider LDAP integration

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/grav_ynh#13]
[This LDAP plugin](https://github.com/trilbymedia/grav-plugin-login-ldap) seems promising for interfacing with YNH as it handles both user-restricted pages and admin panel

- [x] Integrate the plugin
- [x] Configure the plugin with YNH's parameters
- [x] Create admin's user file, including their proper role. (not needed for YNH <3.7)

**Comment by MothGirlMusic** [comment]
has this been worked on? how can i set up the LDAP plugin to work with YunoHost/SSOwat? i've installed it but i'm not sure how YunoHost works with that stuff.

**Comment by tituspijean** [comment]
I have just investigated the matter.

- [Lithrel's basic auth plugin](https://github.com/lithrel/grav-plugin-httpbasicauth) cannot help us log into the admin.
- The [LDAP plugin](https://github.com/trilbymedia/grav-plugin-login-ldap) will most likely work. However, it relies on the use of LDAP groups for permissions. Next YNH version will allow such groups.

I could hack the plugin to ignore groups meanwhile, but I am not sure it is worth it if v3.7 is released soon.

**Comment by tituspijean** [comment]
Well, I found a workaround! It is testable in [v1.6.16 branch](https://github.com/YunoHost-Apps/grav_ynh/tree/v1.6.16) as of https://github.com/YunoHost-Apps/grav_ynh/commit/13c3d01bee93239ac67ddbb2038112962baddee9.

**Comment by Jibec** [comment]
I suggest to wait that yunohost supports apps groups, but you are the one doing the job here.

**Comment by tituspijean** [comment]
Yeah I agree on that point. It will be hell to handle the hacky configuration file, let's keep it on that branch.

**Comment by Jibec** [comment]
Same of php >7.0, ask advice a on irc on what to do, it looks like buster migration is struggling with specific php version.

**Comment by tituspijean** [comment]
With https://github.com/YunoHost-Apps/grav_ynh/commit/54bc307e682893f3967e789116fa5792dec8555a, the branch is now only compatible with v3.7, and the permission system works!
