### ISSUE TITLE
Corrupt source when updating from 1.7.40~ynh1 to 1.7.41.1~ynh1

### ISSUE THREAD

**Issue by borisnoyet** [YunoHost-Apps/grav_ynh#139]
### Description

*Upgrading Grav package from 1.7.40\~ynh1 to  1.7.41.1\~ynh1  interrupts and display a corrupted source message*

### Context

- Hardware: * Mini PC / amd64.*
- YunoHost version: 11.1.19
- I have access to my server: *Through SSH | through the webadmin .*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

- Using, or trying to install package version/branch : from 1.7.40\~ynh1 to  1.7.41.1\~ynh1 
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info grav`*

### Steps to reproduce

- *Upgrade via the web admin or CLI:*
    ```
    sudo yunohost app upgrade grav
    ```
### Logs

*Here is the relevant message — I guess:* ```Corrupt source for /var/cache/yunohost/download/grav/app-upgrade: Expected 6a379c2b5f56d5f93f9481c49e61ca037912cc1def4a0460f3465631b887ae4d but got b664ec3a0da287f3c85dc6ddab68ce294603af4b4068d13388a47989379eeb61 (size: 9.0M	/var/cache/yunohost/download/grav/app-upgrade).```

*A complete log can be found here:* [Log](https://paste.yunohost.org/raw/avukubefet)

**Comment by Bruceumba** [comment]
Same error on new installation.
