### ISSUE TITLE
Grav 1.6 will require php7.1

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/grav_ynh#16]
I want to update the Grave to 1.6 but that will require php7.1 thus breaking the update.
Solution use php7.1 instead of php7.0.

**Comment by Jibec** [comment]
source: https://www.getgrav.org/blog/raising-php-requirements-2018

**Comment by Salamandar** [comment]
I tried (manually) with php7.2 (more future proof as Grav 2.0 will probably require it), and it works flawlessly.
I may work on a PR.

**Comment by Jibec** [comment]
Hello, don't waste time on a PR, if you give an example on another app doing it, it will be sufficient for me.

To be honest, I'm waiting for core to support this feature.

**Comment by rushsteve1** [comment]
Any updates on this?

Grav 1.6 is out and trying to upgrade within Grav complains about needing PHP 7.1.

**Comment by unklebonehead** [comment]
I'm totally new to this yunohost stuff. How do you update Grav and its requirements? Or is it best to just wait for the repo to be upgraded?

**Comment by klorydryk** [comment]
https://github.com/YunoHost-Apps/nextcloud_ynh do it now, on top of php7.3.
What I did to update php used by Grav:
1.  mv /etc/php/7.0/fpm/pool.d/grav.conf 7.3/fpm/pool.d/
2. replace 7.0 by 7.3 in /etc/php/7.3/fpm/grav.conf
3. replace 7.0 by 7.3 in /etc/nginx/conf.d/$DOMAINE$/grav.conf
4. reload nginx and php (sudo systemctl restart nginx and sudo systemctl restart php7.3-fpm.service)

Works like a charm.
