### ISSUE TITLE
nginx 'x-robots-tag' header prevents indexing

### ISSUE THREAD

**Issue by Axolotle** [YunoHost-Apps/grav_ynh#20]
Hey, thanks for the app !

The packaged nginx configuration has a noindex/nofollow header preventing websites from being indexed.

https://github.com/YunoHost-Apps/grav_ynh/blob/2086e6a141d288277caa153e8c716389c739ecf7/conf/nginx.conf#L20

**Comment by Jibec** [comment]
that's a huge mistake, thanks for spotting it!
