### ISSUE TITLE
Twig_Error_Syntax - Unknown "endblock" tag

### ISSUE THREAD

**Issue by vincentux** [YunoHost-Apps/grav_ynh#25]
Suite à la mise jour de Grav, j'ai cette erreur :  

![2019-06-23_17-54-22](https://user-images.githubusercontent.com/11737560/59978744-340d2380-95e0-11e9-9fc2-d4f57e4e7100.png)

```
yunohost
    3.5.2.2 (stable)
yunohost-admin
    3.5.2 (stable)
moulinette
    3.5.2 (stable)
ssowat
    3.5.2.1 (stable) 
```

**Comment by tituspijean** [comment]
Hey, pardon pour la réponse tardive.

Ce genre d'erreur est généralement lié au thème que tu utilises, et au fait que tes pages ne respectent pas le squelette requis par le thème.

Peux-tu donner: 
- le nom du thème que tu utilises (`quark` on dirait),
- le nom de fichier de la page que tu veux charger,
- l'en-tête de cette page?

Par exemple, le thème `learn` nécessite des fichiers nommés `docs.md` ou `chapter.md`, et un en-tête contenant:

```
---
title: Chapter's title
category: docs
---
```

**Comment by vincentux** [comment]
Arf désolé j'ai changé de logiciel...

**Comment by tituspijean** [comment]
Pas de soucis, on avait qu'à être plus réactifs pour répondre aussi ;)
