### ISSUE TITLE
Cannot access to yunohost/sso/ when grav is installed on root domain

### ISSUE THREAD

**Issue by SiM** [YunoHost-Apps/grav_ynh#41]
I installed Grav on my root domain (path '/'), and I cannot anymore access to YunoHost Portal.

When I try to access to `https://root.domain/yunohost/sso/`, it seems to trigger a research on grav website: (I'm redirected to: `https://root.domain/yunohost/sso?q=%2Fyunohost%2Fsso%2F`)

However, no problem to access to YNH admin panel.

Tested both in YNH 3.8 and YNH 4

Grav version: 1.6.26~ynh1

**Comment by tituspijean** [comment]
Bug confirmed on my end. The nginx `location /` supersedes YNH's own `/yunohost` route. I am not sure how to handle that though.

- We could add an exclusion in the location with a regex `location ~ ^/(?!yunohost).*`, but then it would prevent the user from using a page named `yunohost` (little side effect, I admit).
- Something else?

**Comment by SiM** [comment]
> Bug confirmed on my end. The nginx location / supersedes YNH's own /yunohost route. I am not sure how to handle that 

But why does `https://root.domain/yunohost/admin` work and `https://root.domain/yunohost/sso` doesn't?

**Comment by alexAubin** [comment]
That's some super complex stuff related to the way sso works and how it's integrated in nginx .... It's in fact a more general issue than just this app and should be fixed in the core (various folks were investigating and working on a fix yesterday, we have something that should do it)

**Comment by tituspijean** [comment]
@alexAubin can you point me to the potential fix ?
The `location ~ /yunohost/sso { }` does not seem to work in my tests.

**Comment by alexAubin** [comment]
No fix yet but supposedly that was precisely about adding that kind of location :P 

Where did you add it though ? We were thinking about putting it inside the virtual host conf (/etc/nginx/conf.d/domaine.tld.conf)

**Comment by tituspijean** [comment]
v4.0.7 seems to fix the issue, thanks @alexAubin!

I do not know what I was doing wrong with my tests, I was putting the location block right above the main one, in the `grav.conf` nginx config file.

If @SiM confirms it, I will close the issue and bump the version requirement.

**Comment by SiM** [comment]
It works now, thanks !! :tada:
