### ISSUE TITLE
YNH PHP Version is 7/3 but Grav is still reading it as 7.0

### ISSUE THREAD

**Issue by brimwats** [YunoHost-Apps/grav_ynh#43]
Cannot install any extensions right now unfortunately.

**Comment by tituspijean** [comment]
The `install` script specifically asks from PHP 7.3, so I do not see any issue on this end.
Please, as always, for any issue related to computers, **_provide the logs_**.

**Comment by brimwats** [comment]
> The `install` script specifically asks from PHP 7.3, so I do not see any issue on this end.
> Please, as always, for any issue related to computers, **_provide the logs_**.

There aren't really any logs as it installed normally fine. However I unininstalled and reinstalled for you: https://paste.yunohost.org/raw/cepisolafu


when I go to /var/www/grav and run the plugin commands I get

```
root@DOMAIN:/var/www/grav# bin/gpm index
You are running PHP 7.0.33-30+0~20200807.37+debian10~1.gbp047872, but Grav needs at least PHP 7.1.3 to run.
```

**Comment by brimwats** [comment]
ah—i'm an idiot and needed to run

> sudo update-alternatives --set php /usr/bin/php7.3

**Comment by tituspijean** [comment]
Ooooh I see now.

AFAIK, since YNH can have multiple PHP versions installed, a better way to do so is to specifically call the binary :

`php7.3 bin/gpm index`
