### ISSUE TITLE
Consider skeleton support

### ISSUE THREAD

**Issue by zyphlar** [YunoHost-Apps/grav_ynh#47]
The Grav style of creating and referencing modulars was super difficult for me to get started with even as a web developer / sysadmin / blogger. Using Grav's skeletons to get started helped me out a lot, but they seem to take the place of the entire root folder which precludes much of this package's installation routine.

Perhaps if there was a YNH / grav_ynh script command or documentation that showed how to blow away the default installation and replace it with a skeleton zip, this could at least be easier. I seem to have done it myself by installing grav_ynh and then following the installation script more or less manually, but I'm worried that eventually I'll run into upgrade or other issues.

**Comment by tituspijean** [comment]
This package currently "simply" gets the Grav core+admin zip file, checks its integrity, unzips it into `/var/www/grav`, and makes all the system/nginx-side arrangements to make it work.

What your are suggesting is allowing the user to specify which zip file to download, and frankly that would be hell to handle automagically. There are currently 51 skeleton files, all with different versions, and it would require monitoring as many integrity hashes...

However, the good news is that upgrading the app simply dumps the update zip file into `/var/www/grav`. Installing a skeleton would basically be unzipping the skeleton file over there and replace existing files. You can do that by FTP or command line, but bear in mind you need to `chown -R grav:www-data /var/www/grav` afterwards.

**Comment by ashledombos** [comment]
Hello,
I tried with this [skeleton](https://github.com/hibbitts-design/grav-skeleton-open-publishing-space)

```
wget http://hibbittsdesign.org/blog/downloads/grav-skeleton-open-publishing-space-site.zip
unzip grav-skeleton-open-publishing-space-site.zip
yes | cp -rf grav-skeleton-open-publishing-space-site/* /var/www/grav/
```
(I had to pipe with a yes to avoid to confirm each overwrite, despite the -f switch. I guess because of an alias in bashrc, but did not investigate)
```
chown -R grav:www-data /var/www/grav
rm -rf grav-skeleton-open-publishing-space-site*
```

And it worked like a charm.

**Comment by ashledombos** [comment]
_And it worked like a charm._
Well not totally, I was speaking too quickly. In fact there are some glitches in visual rendering (I noticed the breadcrumb is badly rendered)

So I tried another way which seems to work better, to move the yunohost package content in a temporary directory, put the skeleton instead, and then copy the content from yunohost package that doesn't exist in skeleton:

```
mv /var/www/grav /var/www/grav_temp
wget http://hibbittsdesign.org/blog/downloads/grav-skeleton-open-publishing-space-site.zip
unzip grav-skeleton-open-publishing-space-site.zip
mv grav-skeleton-open-publishing-space-site /var/www/grav
cp -nr /var/www/grav_temp/* /var/www/grav
chown -R grav:www-data /var/www/grav
rm -rf grav-skeleton-open-publishing-space-site*
```
and if you think you don't need it anymore:
`rm -rf /var/www/grav_temp`

With this technique, I have the expected rendering and ldap connection is working.

**Comment by tituspijean** [comment]
Glad it worked overall!

Did you reset Grav's cache after installing the skeleton? I often get those glitches when I tweak themes.

**Comment by ashledombos** [comment]
No, maybe I should, I'll restart the whole process and tell, then.
