### ISSUE TITLE
Grav update failed (from 1.5.3~ynh2 to 1.7.5~ynh1)

### ISSUE THREAD

**Issue by marjorii** [YunoHost-Apps/grav_ynh#58]
### Describe the bug

Hello !

I upgraded successfully my system to buster, but now my grav instance seems inaccessible (502) and the grav upgrade is failing (see logs below). Every services are running and diagnosis is okay. Also, I upgrated nextcloud with no trouble. Thanks in advance for your help !

### Context

- Hardware: *VPS bought online*
- YunoHost version: *4.1.7.1 (stable)*
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: *no*
- Trying to install package version: *1.7.5~ynh1 (master ?)*
- Current package version: *1.5.3~ynh2*

### Steps to reproduce

Simply try to upgrade grav from yunohost admin.

### Logs
Relevant part: 
```
PHP Fatal error: require_once(): Failed opening required '/var/www/grav/user/plugins/admin/classes/admin.php' (include_path='.:/usr/share/php') in /var/www/grav/user/plugins/admin/admin.php on line 122
```
Whole error report: 
https://paste.yunohost.org/raw/tanayiyiqo

**Comment by tituspijean** [comment]
It feels like a Grav bug. :/ Can you try upgrading from Grav's webadmin? 🤞

**Comment by marjorii** [comment]
Hey !

Thanks for your answer ! Unfortunately, the grav webadmin leads to a 502 bad gateway ! Restarting nginx was useless too. Maybe I should try an update with the cli ?

**Comment by Axolotle** [comment]
Hey ; )

I get the same error while upgrading from 1.6.28~ynh1 to 1.7.5~ynh1
```
PHP Fatal error:  require_once(): Failed opening required '/var/www/grav/user/plugins/admin/classes/admin.php' (include_path='.:/usr/share/php') in /var/www/grav/user/plugins/admin/admin.php on line 122
```
But the auto restore is ok, my grav instance is running. I'm gonna try to upgrade with `bin/gpm` and see if it breaks the instance.

**Comment by tituspijean** [comment]
@marjorii, @Axolotle, let's try to debug that if you are willing to do so. :) Bear in mind you can roll back to before your first upgrade attempt with the backups made by YunoHost.

Right after generating a 500/502 error, can you share the contents of `tail -n 50 /var/log/nginx/YOURDOMAIN-error.log` ?

**Comment by marjorii** [comment]
Here's the log I got : 
```
2021/02/21 17:52:06 [error] 19032#19032: *234 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught RuntimeException: Failed to save file /var/www/grav/cache/compiled/files/740eb2f059012e0c1e8190de3b06137a.yaml.php in /var/www/grav/vendor/rockettheme/toolbox/File/src/AbstractFile.php:369
Stack trace:
#0 /var/www/grav/vendor/rockettheme/toolbox/File/src/PhpFile.php(41): RocketTheme\Toolbox\File\AbstractFile->save(Array)
#1 /var/www/grav/system/src/Grav/Common/File/CompiledFile.php(76): RocketTheme\Toolbox\File\PhpFile->save(Array)
#2 /var/www/grav/system/src/Grav/Common/Config/CompiledConfig.php(111): Grav\Common\File\CompiledYamlFile->content()
#3 /var/www/grav/system/src/Grav/Common/Config/CompiledBase.php(180): Grav\Common\Config\CompiledConfig->loadFile('themes/website_...', '/var/www/grav/u...')
#4 /var/www/grav/system/src/Grav/Common/Config/CompiledBase.php(112): Grav\Common\Config\CompiledBase->loadFiles()
#5 /var/www/grav/system/src/Grav/Common/Config/CompiledConfig.php(61): Grav\Common\Config\CompiledBase->load()
#6 /var/www/grav/system/src/Grav/Co" while reading response header from upstream, client: 81.56.104.17, server: marjorieober.com, request: "GET /home/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm-grav.sock:", host: "marjorieober.com"
2021/02/21 17:52:10 [error] 19032#19032: *236 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught RuntimeException: Failed to save file /var/www/grav/cache/compiled/files/740eb2f059012e0c1e8190de3b06137a.yaml.php in /var/www/grav/vendor/rockettheme/toolbox/File/src/AbstractFile.php:369
Stack trace:
#0 /var/www/grav/vendor/rockettheme/toolbox/File/src/PhpFile.php(41): RocketTheme\Toolbox\File\AbstractFile->save(Array)
#1 /var/www/grav/system/src/Grav/Common/File/CompiledFile.php(76): RocketTheme\Toolbox\File\PhpFile->save(Array)
#2 /var/www/grav/system/src/Grav/Common/Config/CompiledConfig.php(111): Grav\Common\File\CompiledYamlFile->content()
#3 /var/www/grav/system/src/Grav/Common/Config/CompiledBase.php(180): Grav\Common\Config\CompiledConfig->loadFile('themes/website_...', '/var/www/grav/u...')
#4 /var/www/grav/system/src/Grav/Common/Config/CompiledBase.php(112): Grav\Common\Config\CompiledBase->loadFiles()
#5 /var/www/grav/system/src/Grav/Common/Config/CompiledConfig.php(61): Grav\Common\Config\CompiledBase->load()
#6 /var/www/grav/system/src/Grav/Co" while reading response header from upstream, client: 81.56.104.17, server: marjorieober.com, request: "GET /home/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm-grav.sock:", host: "marjorieober.com"
```

**Comment by Axolotle** [comment]
On my side, upgrading with `bin/gpm` rethrow the same error as before but updated ok. I had a problem with the `assets/` folder permissions but everything is updated and accessible.
But i see my file permissions are a huge mess, WHOOPSIES. i have root for file/folder owner on some folders, i may have messed with this some while ago. How could i apply recommended file/folder permissions to the whole ?

I must add that both marjorii and i are using a custom theme installed by a git clone in the `theme/` folder. So maybe her problem is related to file permission as well.

**Comment by marjorii** [comment]
Hello !

Thanks for your help ! After a few more investigation, it turns out that it was related to a file permission problem.
