### ISSUE TITLE
[stretch] PHP Zip extension is not installed

### ISSUE THREAD

**Issue by Salamandar** [YunoHost-Apps/grav_ynh#6]
On stretch (yeah I know, not supported and all, but still), the grav homepage tells "PHP Zip extension is not installed".
Installing the package `php-zip` solves the problem.

**Comment by tituspijean** [comment]
https://github.com/YunoHost-Apps/grav_ynh/pull/8 should solve this issue, and make the app support Stretch.

**Comment by tituspijean** [comment]
9d464b5 resolved this issue.
