### ISSUE TITLE
Broken installation via webadmin, broken LDAP / Login

### ISSUE THREAD

**Issue by m0rtis0** [YunoHost-Apps/grav_ynh#65]
### Describe the bug

When trying to install the App via the Web admin panel, it freezes before I can click Install, the ask selections for domain and admin user cannot be accessed, it only shows a loading indicator forever.
Also, when trying to install via CLI (which works) and then trying to login, no user is able to login. grav.user and grav.admin permissions are given to a user, but when trying to login, it just rejects with "login failed.."
There are no meaningful logs in /var/www/grav/user/logs/grav.log or nginx or php-fpm. The normal behaviour that the grav LDAP plugin logs access rejections to this log is not present, the log only contains infos about flex-objects.

The app is broken because of these issues and can not be used

### Context

- Hardware: Contabo VPS L SSD
- YunoHost version: 4.1.7.4 (stable)
- I have access to my server: SSH + Webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: no
  - If yes, please explain:
- Using, or trying to install package version/branch: latest (1.7.7)
- If upgrading, current package version: -

### Steps to reproduce

- Install via cli
    ```sh
    sudo yunohost app install grav
    ```
- Assign grav.admin and grav.user perms to user/group
- Try to login with the user
- Fails wiith "Failed to login..."
- No logs are produced of the incident

### Expected behavior

Installation via Webadmin works
Login with authorized user works

### Logs

Logs are empty! No Grav-related info/error messages produced, apart from the nginx 200 entries in the access logs, which are not very helpful

**Comment by Aeris1One** [comment]
Seems to be a drawback of https://github.com/YunoHost-Apps/grav_ynh/commit/380d91cf6749da42f1f13b62c54da8a3d1ac5ca4#diff-ffa5b716b5a57837f7929dfcca4b4dfdeb97210a7fd5a12d2f1978846d6f1743

**Comment by tituspijean** [comment]
It seems the LDAP plugin is not installed anymore during the installation... Running `sudo -u grav /var/www/grav/bin/gpm install login-ldap -n` solves the issue.

**Comment by Aeris1One** [comment]
> When trying to install the App via the Web admin panel, it freezes before I can click Install, the ask selections for domain and admin user cannot be accessed, it only shows a loading indicator forever.
Seems to be a problem with manifest handling in webadmin, right ?

**Comment by taranta-babu** [comment]
> It seems the LDAP plugin is not installed anymore during the installation... Running `cd /var/www/grav` then `sudo -u grav bin/gpm install login-ldap -n` solves the issue.
> 
> The current method, does not work:
> 
> ```
> 2021-04-05 11:41:58,262: DEBUG - + sudo -u grav php7.3 /var/www/grav/bin/gpm install login-ldap --all-yes --no-interaction
> 2021-04-05 11:41:58,362: DEBUG - FATAL: Must be run from ROOT directory of Grav!
> ```

Hello ! I had the same issue,  `sudo -u grav bin/gpm install login-ldap -n` worked well thank you. However cache/gpm was owned by root so I had to change the owner.

**Comment by tituspijean** [comment]
Glad it worked for you! 

> I've another issue however: when I go to mydomain.com/ where grav is install it's redirecting to mydomain.com/grav and give a 404 error. When I go to mydomain.com/home it gives me the standard home page. Would you know what is happening?

Please open a dedicated issue for that. ;)

**Comment by tituspijean** [comment]
Fixed by #67.
