### ISSUE TITLE
does not work well if site is at root location

### ISSUE THREAD

**Issue by ljubomirb** [YunoHost-Apps/grav_ynh#71]
When I set my website to be at root (/) as www.mysite.com in yunohost, and also click "make default",
and then open site in browser, browser gets redirected to mysite.com/grav.

I did not expect that, and I would prefer not to have it like that. 
I tried clearing cache from chrome and grav, and looked into config files, and I do not see anything in www.mysite.com.config or www.mysite.com.d/grav nginx that is obvious.
The only thing I tried is to comment line in https server confing on www.mysite.com.conf

`#    access_by_lua_file /usr/share/ssowat/access.lua;`

and after that, no redirection happens, and also, grav can still be accessed from browser at www.mysite.com/admin

I might be missing some config button to click or is this planned to be like this? If so, it's not the best solution, and complicates things on other places...

**Comment by tituspijean** [comment]
I am sorry, I cannot replicate your issue. I have tried:
- installing at root, and made default
- installing at path, made default, changed url to root
- installing at path, changed url to root, made default

Your test by commenting out the access Lua script may indicate an issue with ssowat. Can you try regenerating its configuration with `yunohost app ssowatconf`?

**Comment by ljubomirb** [comment]
Typing `yunohost app ssowatconf` does not show any return, but shows no error either.

With lua off, return code is 200, all works as expected. With lua on, it is 302, then browser tries to open www.mysite.com/grav and gets 404

Trying to set my web page to be default at root again returns this error:
![this error](https://user-images.githubusercontent.com/10389689/125494887-69e34cef-ecd1-4c9c-b814-053ebbedaf12.jpg)

If I knew it has to do with grav only, I would uninstall grav, install it again, copy themes, pages...

**Comment by ljubomirb** [comment]
So, I removed grav, installed again, this time at / and www.mysite.com.
What I notice is that at all times, grav menu is shown, and I can click Grav, Home and Typography. If i click Typography, then it works, page is opened. If I click Home or Grav, it has same 404 error, browser trying to open /grav page that does not exist, being redirected (only guessing) buy lua file.
If I change (in www.mysite.com/admin page) for grav homepage to by Typography, then that page is has problem, other pages (home, Grav) open normal, because they no longer point to /.
I'm running out of ideas, I could look at that lua file, but that would be a pain for me...

**Comment by tituspijean** [comment]
Considering it's a year-old issue, and not replicable, I'm opting to close.
Feel free to open a thread on our forum for further debugging.
