### ISSUE TITLE
Way too big backups

### ISSUE THREAD

**Issue by Aeris1One** [YunoHost-Apps/grav_ynh#88]
### Describe the bug

I backup my apps using Borg backup (which itself uses the intern mechanism for creating backups) and, while my website is basically only a single page (with barely default config), four of those backups were 4.5+ Gb when deduplicated (you can read this as "weight of one backup"), and so 14+ Gb in total for only 4 of them ! 
I deleted them as my website's only a "Welcome, there's nothing here atm !" page it doesn't need backups, especially if they are that big :/

Any idea why ?

![image](https://user-images.githubusercontent.com/29739547/145275022-332957e8-be67-4b68-816e-c40e32ddffda.png)
(In this image, deleted data refers to Grav's backups, total means all my others backups from all others apps)

### Context

- Hardware: VPS
- YunoHost version: 4.3
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
  - If yes, please explain:
- Using, or trying to install package version/branch: stable

**Comment by tituspijean** [comment]
Grav has an internal backup feature that you should disable. I can investigate how to have it turned off by default, but not before this weekend. 😇

**Comment by tituspijean** [comment]
I have created the mentioned PR above. This will fix the issue on new installs, but I am not sure it is a good idea to tweak existing configuration.

If you want to disable daily backup, you may find the setting in Grav's admin panel, or in `/var/www/grav/user/config/scheduler.yaml`, under `default-site-backup`. Backups are in `/var/www/grav/backup`.
